 define({
      "title" : "带饭大哥",
      "brand" : "带饭大哥",
      "barTitle" : "带饭大哥",
      "orderDish" : "订餐",
      "statusCheck" : "送餐状态查询",
      "mobileOrder" : "订餐",
      "mobileStatus" : "送餐状态查询",
      "dishTitle" : "今日可选菜品",
      "orderMessage" : "带饭大哥每天中午12:00~12:30会送餐到马大，请各位顾客老爷小姐注意查看送餐状态,准时取餐",
      "paymentBtn" : "大哥，买单!",
      "orderDetails" : "您的订单如下:",
      "summary-count" : "份",
      "summary-tax-label" : "税和运费",
      "summary-total-label" : "合计：",
      "nameOnOrder" : "取餐人：",
      "pickUpAddress" : "取餐地点：",
      "thanks" : "您的订单已经受理，感谢您使用带饭大哥的服务!",
    });